# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pgvector-db.labels" . | nindent 4 }}
  name: {{ include "pgvector-db.fullname" . }}
spec:
  ports:
    - name: "{{ .Values.service.port }}"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "pgvector-db.selectorLabels" . | nindent 4 }}
